// <auto-generated />
using System;
using BookHive;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookHive.Migrations
{
    [DbContext(typeof(BookHiveDbContext))]
    [Migration("20260309143217_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookHive.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1913, 11, 7),
                            FirstName = "Albert",
                            LastName = "Camus",
                            Nationality = "Française"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1920, 10, 8),
                            FirstName = "Frank",
                            LastName = "Herbert",
                            Nationality = "Américaine"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1965, 7, 31),
                            FirstName = "J.K.",
                            LastName = "Rowling",
                            Nationality = "Britannique"
                        });
                });

            modelBuilder.Entity("BookHive.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Genre = "Roman",
                            Isbn = "9782070360024",
                            PageCount = 184,
                            PublishedDate = new DateOnly(1942, 6, 15),
                            Title = "L'Étranger"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Genre = "Roman",
                            Isbn = "9782070360420",
                            PageCount = 352,
                            PublishedDate = new DateOnly(1947, 6, 10),
                            Title = "La Peste"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Genre = "Science-Fiction",
                            Isbn = "9782266233200",
                            PageCount = 712,
                            PublishedDate = new DateOnly(1965, 8, 1),
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Genre = "Science-Fiction",
                            Isbn = "9782266233217",
                            PageCount = 320,
                            PublishedDate = new DateOnly(1969, 1, 1),
                            Title = "Le Messie de Dune"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Genre = "Fantasy",
                            Isbn = "9782070518425",
                            PageCount = 305,
                            PublishedDate = new DateOnly(1997, 6, 26),
                            Title = "Harry Potter à l'école des sorciers"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Genre = "Fantasy",
                            Isbn = "9782070541295",
                            PageCount = 361,
                            PublishedDate = new DateOnly(1998, 7, 2),
                            Title = "Harry Potter et la Chambre des secrets"
                        });
                });

            modelBuilder.Entity("BookHive.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LoanDate")
                        .HasColumnType("date");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateOnly(2026, 2, 4),
                            LoanDate = new DateOnly(2026, 1, 5),
                            MemberId = 1,
                            ReturnDate = new DateOnly(2026, 1, 20)
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateOnly(2026, 2, 9),
                            LoanDate = new DateOnly(2026, 1, 10),
                            MemberId = 2,
                            ReturnDate = new DateOnly(2026, 2, 1)
                        },
                        new
                        {
                            Id = 3,
                            BookId = 5,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateOnly(2026, 2, 28),
                            LoanDate = new DateOnly(2026, 2, 1),
                            MemberId = 3,
                            ReturnDate = new DateOnly(2026, 2, 15)
                        },
                        new
                        {
                            Id = 4,
                            BookId = 3,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateOnly(2026, 3, 30),
                            LoanDate = new DateOnly(2026, 3, 1),
                            MemberId = 1
                        },
                        new
                        {
                            Id = 5,
                            BookId = 6,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateOnly(2026, 4, 4),
                            LoanDate = new DateOnly(2026, 3, 5),
                            MemberId = 2
                        });
                });

            modelBuilder.Entity("BookHive.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("MembershipDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jean.dupont@email.com",
                            FirstName = "Jean",
                            IsActive = true,
                            LastName = "Dupont",
                            MembershipDate = new DateOnly(2025, 1, 10)
                        },
                        new
                        {
                            Id = 2,
                            Email = "marie.curie@email.com",
                            FirstName = "Marie",
                            IsActive = true,
                            LastName = "Curie",
                            MembershipDate = new DateOnly(2025, 2, 15)
                        },
                        new
                        {
                            Id = 3,
                            Email = "lucas.bernard@email.com",
                            FirstName = "Lucas",
                            IsActive = true,
                            LastName = "Bernard",
                            MembershipDate = new DateOnly(2025, 3, 1)
                        },
                        new
                        {
                            Id = 4,
                            Email = "sophie.martin@email.com",
                            FirstName = "Sophie",
                            IsActive = false,
                            LastName = "Martin",
                            MembershipDate = new DateOnly(2025, 1, 20)
                        });
                });

            modelBuilder.Entity("BookHive.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("BookId", "MemberId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Comment = "Un classique absolu.",
                            CreatedAt = new DateTime(2026, 3, 9, 15, 32, 16, 601, DateTimeKind.Local).AddTicks(4314),
                            MemberId = 1,
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            Comment = "L'univers est incroyablement riche.",
                            CreatedAt = new DateTime(2026, 3, 9, 15, 32, 16, 601, DateTimeKind.Local).AddTicks(4318),
                            MemberId = 2,
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            BookId = 5,
                            Comment = "Très bonne introduction à la magie.",
                            CreatedAt = new DateTime(2026, 3, 9, 15, 32, 16, 601, DateTimeKind.Local).AddTicks(4321),
                            MemberId = 3,
                            Rating = 4
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            Comment = "Une lecture poignante.",
                            CreatedAt = new DateTime(2026, 3, 9, 15, 32, 16, 601, DateTimeKind.Local).AddTicks(4324),
                            MemberId = 1,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("BookHive.Entities.Book", b =>
                {
                    b.HasOne("BookHive.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookHive.Entities.Loan", b =>
                {
                    b.HasOne("BookHive.Entities.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookHive.Entities.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BookHive.Entities.Review", b =>
                {
                    b.HasOne("BookHive.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookHive.Entities.Member", "Member")
                        .WithMany("Reviews")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BookHive.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookHive.Entities.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("BookHive.Entities.Member", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
